export const webPagesList = [
    {
        id: 1,
        name: "Professional Portfolio V1",
        image: "https://i.imgur.com/bmY9wK6.png",
        repo: "https://github.com/5arSanti/PortafolioV1-Santiago-Arias",
        homeLink: "https://5arsanti.github.io/PortafolioV1-Santiago-Arias/",
    },
    {
        id: 2,
        name: "Yard Sale Shop",
        image: "https://i.imgur.com/HZ0yXma.png",
        repo: "https://github.com/5arSanti/Curso_Practico_FrontEnd_Platzi",
        homeLink: "https://5arsanti.github.io/Curso_Practico_FrontEnd_Platzi/",
    },
    {
        id: 3,
        name: "Async landing Portfolio",
        image: "https://i.imgur.com/SaNTTE2.png",
        repo: "https://github.com/5arSanti/async-landing",
        homeLink: "https://5arsanti.github.io/async-landing/",
    },
    {
        id: 4,
        name: "TODO Machine",
        image: "http://imagizer.imageshack.com/img922/4475/f3L6wk.png",
        repo: "https://github.com/5arSanti/Curso-de-React-js",
        homeLink: "https://5arsanti.github.io/Curso-de-React-js/",
    },
    {
        id: 5,
        name: "Shopi E-commerce",
        image: "https://i.imgur.com/fvgnK5n.png",
        repo: "https://github.com/5arSanti/Curso-de-React-js-con-Vite-js-y-TailwindCSS",
        homeLink: "https://lambent-snickerdoodle-61f33d.netlify.app/",
    },
    {
        id: 6,
        name: "Sunrise Mirror",
        image: "https://i.imgur.com/y4Kk10E.png",
        repo: "https://github.com/5arSanti/Sunrise-Mirror",
        homeLink: "https://5arsanti.github.io/Sunrise-Mirror/",
    },
    {
        id: 7,
        name: "Blog Personal",
        image: "https://i.imgur.com/7mXHc1n.png",
        repo: "https://github.com/5arSanti/Curso-Practico-de-Maquetacion-en-CSS",
        homeLink: "https://5arsanti.github.io/Curso-Practico-de-Maquetacion-en-CSS/",
    },
    {
        id: 8,
        name: "Animationland",
        image: "https://i.imgur.com/kWodtKz.png",
        repo: "https://github.com/5arSanti/Curso-de-Animaciones-con-CSS",
        homeLink: "https://5arsanti.github.io/Curso-de-Animaciones-con-CSS/",
    },
    {
        id: 9,
        name: "Portafolio Profesional",
        image: "https://i.imgur.com/6nCsDWt.png",
        repo: "https://github.com/5arSanti/5arSanti.github.io",
        homeLink: "",
    },
]